version: "3"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_PORT=$DATABASE_PORT
  web:
#    build: .
    image: tictactoe:latest
    command: >
      bash -c "python TicTacToe/manage.py migrate
      && python TicTacToe/manage.py runserver 0.0.0.0:8080"
    environment:
    - DATABASE_NAME=$DATABASE_NAME
    - DATABASE_USER=$DATABASE_USER
    - DATABASE_PASSWORD=$DATABASE_PASSWORD
    - DATABASE_HOST=$DATABASE_HOST
    - DATABASE_PORT=$DATABASE_PORT
    - SECRET_KEY=$SECRET_KEY
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db