# Generated by Django 3.1.6 on 2021-02-19 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_progress', models.BooleanField(default=True)),
                ('win', models.BooleanField(default=False)),
                ('start_time', models.FloatField(blank=True, null=True)),
                ('finish_time', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('player_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_o_games', to=settings.AUTH_USER_MODEL)),
                ('player_x', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_x_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_field', models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1)),
                ('second_field', models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1)),
                ('third_field', models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1)),
                ('fourth_field', models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1)),
                ('fifth_field', models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1)),
                ('sixth_field', models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1)),
                ('seventh_field', models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1)),
                ('eighth_field', models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1)),
                ('ninth_field', models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1)),
                ('last_move', models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O')], max_length=1)),
                ('end_game', models.BooleanField(default=False)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
