# Generated by Django 3.1.4 on 2021-02-06 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='end_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AddField(
            model_name='board',
            name='last_move',
            field=models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O')], max_length=1),
        ),
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player_o',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_o_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='player_x',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_x_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='eighth_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='fifth_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='first_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='fourth_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='ninth_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='second_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='seventh_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='sixth_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='third_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default=' ', max_length=1),
        ),
    ]
