# Generated by Django 3.1.4 on 2021-01-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210130_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='player_o',
        ),
        migrations.RemoveField(
            model_name='board',
            name='player_x',
        ),
    ]
