# Generated by Django 3.1.4 on 2021-01-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210130_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='eighth_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='fifth_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='first_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='fourth_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='ninth_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='second_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='seventh_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='sixth_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='third_field',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O'), (' ', ' ')], default='', max_length=1),
        ),
    ]
