# Generated by Django 3.1.4 on 2021-02-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210130_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='last_move',
            field=models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O')], max_length=1),
        ),
    ]
