# Generated by Django 3.1.4 on 2021-01-10 15:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='best_game_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='game_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='lose_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='time_spend_in_game',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='win_counter',
            field=models.IntegerField(default=0),
        ),
    ]
